# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapi-app-muraly

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com//
        username: ${{ secrets.AzureAppService_ContainerUsername_96148be11bc44a3399f9fb039c44e5d9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9114ad25dce84306b0f22dc4f472e86f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com//${{ secrets.AzureAppService_ContainerUsername_96148be11bc44a3399f9fb039c44e5d9 }}/strapitest123:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapi-app-muraly'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4aaf097e32474036bc60e5c77dbbf952 }}
        images: 'mcr.microsoft.com//${{ secrets.AzureAppService_ContainerUsername_96148be11bc44a3399f9fb039c44e5d9 }}/strapitest123:${{ github.sha }}'