# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapi-app-muraly

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2cf31e9bb754664a5c4772f53a5db4c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ceebc549ae2b4f3abb32621fc1b69d95 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f2cf31e9bb754664a5c4772f53a5db4c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapi-app-muraly'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5aada90675ef40cdb1d9b779e2c69f5f }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f2cf31e9bb754664a5c4772f53a5db4c }}/appsvc/staticsite:${{ github.sha }}'